// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApp.Data;

namespace WebApp.Migrations.Renta
{
    [DbContext(typeof(RentaContext))]
    [Migration("20200608143211_Renta1")]
    partial class Renta1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApp.Models.Kola", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(40)");

                    b.Property<byte>("BrojMesta")
                        .HasColumnType("tinyint");

                    b.Property<short>("Godiste")
                        .HasColumnType("smallint");

                    b.Property<string>("Naziv")
                        .HasColumnType("nvarchar(40)");

                    b.Property<byte>("TipVozila")
                        .HasColumnType("tinyint");

                    b.HasKey("ID");

                    b.ToTable("Kolas");
                });

            modelBuilder.Entity("WebApp.Models.Misc.Ocena", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("UserID")
                        .HasColumnType("nvarchar(40)");

                    b.Property<byte>("Val")
                        .HasColumnType("tinyint");

                    b.HasKey("ID");

                    b.ToTable("Ocene");
                });

            modelBuilder.Entity("WebApp.Models.Misc.Zauzetost", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime>("Do")
                        .HasColumnType("date");

                    b.Property<string>("KolaID")
                        .HasColumnType("nvarchar(40)");

                    b.Property<DateTime>("Od")
                        .HasColumnType("date");

                    b.HasKey("ID");

                    b.ToTable("Zauzetosts");
                });

            modelBuilder.Entity("WebApp.Models.RentACar", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(40)");

                    b.Property<string>("AdminID")
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("ID");

                    b.ToTable("Rente");
                });
#pragma warning restore 612, 618
        }
    }
}
